#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Application rules
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" manage=off sticky=on layer=above
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Google Chrome$" manage=on
yabai -m rule --add app="^Spotify$" manage=off opacity=1
yabai -m rule --add app="^Telegram$" manage=off opacity=1
yabai -m rule --add app="^Viber$" manage=off opacity=1
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Keynote$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^Voice Memos$" manage=off
yabai -m rule --add app="^Text Edit$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Code$" manage=on
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Quick Time Player$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Microsoft Word$" manage=off
yabai -m rule --add app="^Microsofy Excel$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Numbers$" manage=off
yabai -m rule --add app="^TextEdit$" manage=off
yabai -m rule --add app="^Notes$" manage=off sticky=on layer=above
yabai -m rule --add app="^Reminders$" manage=off sticky=on layer=above
yabai -m rule --add app="^Calendar$" manage=off sticky=on

# Window placement
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on

# Window opacity
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1
yabai -m config normal_window_opacity 0.95

# Borders
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xFF009E60
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_feedback_color 0xffd75f5f

# General
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

# Padding
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

# Focus on a new window upon closing one
yabai -m signal --add event=window_destroyed action="bash /Users/bastinodalo/CustomScripts/SwitchSpaces/window-focus-on-destroy.sh"

# Limelight for when SIP is enabled 
export PATH=/usr/local/bin:$PATH
# killall limelight &> /dev/null
# limelight &> /dev/null &

echo "yabai configuration loaded.."

#END
